### ISSUE TITLE
Drafts?

### ISSUE THREAD

**Issue by martinschimak** [blevesearch/hugoidx#5]
I have a question: how does the command currently deal with drafts. Is there a way to exclude/include them? Many thx!

**Comment by mschoch** [comment]
I originally tried to write the tool to reuse the hugo flags, so that we could honor the `-D` flag the same way when walking the site.  But, it's pretty clear that didn't work.  I didn't really know much about `spf13/cobra` at the time, but I've used it for another project now, so I should revisit and figure out the right way to do this.

There is a separate problem that the methods we use to walk the site's pages seem to have changed/disappeared from the current version of hugo.  @spf13 had suggested we post to the hugo forums in the past, now might be the right time to do that, and find a long-term supportable way for external tools to hook-in to the hugolib process.

**Comment by mschoch** [comment]
This project has been neglected for some time, and no longer works with any recent version of hugo.  We are archiving this project.
