### ISSUE TITLE
function "readFile" not defined

### ISSUE THREAD

**Issue by vickychijwani** [blevesearch/hugoidx#7]
Hi, I have some docs that use the following Hugo shortcode defined in layouts/shortcodes/readfile.html:

```
{{ .Get 0 | readFile | htmlEscape | chomp }}
```

This works just fine with recent Hugo versions (currently at v0.19). But when I run hugoidx, I get this error:

```
ERROR: 2017/03/01 19:30:07 template.go:350: template: shortcodes/readfile.html:1: function "readFile" not defined
ERROR: 2017/03/01 19:30:07 shortcode.go:266: Failed to handle template for shortcode 'readfile' for page 'my-page-1': Template failed to compile
ERROR: 2017/03/01 19:30:07 shortcode.go:266: Failed to handle template for shortcode 'readfile' for page 'my-page-2': Template failed to compile
```

I assumed this was because the vendored hugo dependency is too old (#6), but even after updating hugo to the latest version, I still see the same error (readFile not defined). Where am I going wrong? Or is the error simply misleading because hugo isn't designed to be called as a library? (as pointed out in #6)

**Comment by mschoch** [comment]
I'm afraid I don't have a good fix to suggest.  It definitely won't work with newer versions, which is why we vendored the older version.  As for the short codes, I'm not sure if that ever worked.  I just dont remember if the bleve site used any custom short codes or not.

One of the suggestions in #6 is to use Hugo to generate JSON pages for your site, and then indexing those with bleve.  This sounds like it may be our past path forward.  Can you add a comment on that issue with your thoughts on that approach?

**Comment by mschoch** [comment]
This project has been neglected for some time, and no longer works with any recent version of hugo.  We are archiving this project.
